[package]
name = "sd-experiment"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = "1.0.104"
csv = "1.4.0"
itertools = "0.14.0"
sd-core = { path = "../sd-core" }
sd-graphics = { path = "../sd-graphics" }

[dev-dependencies]
cargo-husky = { version = "1.5.0", features = ["precommit-hook", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"] }
dir-test = "0.4.1"
insta = { version = "1.42.2", features = ["ron"] }
serde = "1.0.218"

[features]
default = []
microlp = ["sd-graphics/microlp"]
cbc = ["sd-graphics/cbc"]
highs = ["sd-graphics/highs"]
gurobi = ["sd-graphics/gurobi"]
