variable = @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC* }
bind_clause = { "bind" ~ variable ~ "=" ~ term ~ "in" }
expr = { bind_clause* ~ value }
term = { thunk | (active_op ~ "(" ~ args ~ ")") | value }
value = { (passive_op ~ "(" ~ args ~ ")") | variable }
active_op = { "+" }
passive_op = { number }
number = _{ ASCII_DIGIT+ }
args = _{ value ~ ("," ~ value)* | "" }
program = _{ SOI ~ expr ~ EOI }
WHITESPACE = _{ " " | "\n" }
thunk = { variable* ~ "." ~ expr }